scrape_configs:
  - job_name: 'TontteryMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Tonttery Service'